# coding: utf-8

"""
    SendinBlue API

    SendinBlue provide a RESTFul API that can be used with any languages. With this API, you will be able to :   - Manage your campaigns and get the statistics   - Manage your contacts   - Send transactional Emails and SMS   - and much more...  You can download our wrappers at https://github.com/orgs/sendinblue  **Possible responses**   | Code | Message |   | :-------------: | ------------- |   | 200  | OK. Successful Request  |   | 201  | OK. Successful Creation |   | 202  | OK. Request accepted |   | 204  | OK. Successful Update/Deletion  |   | 400  | Error. Bad Request  |   | 401  | Error. Authentication Needed  |   | 402  | Error. Not enough credit, plan upgrade needed  |   | 403  | Error. Permission denied  |   | 404  | Error. Object does not exist |   | 405  | Error. Method not allowed  | 

    OpenAPI spec version: 3.0.0
    Contact: contact@sendinblue.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import sib_api_v3_sdk
from sib_api_v3_sdk.rest import ApiException
from sib_api_v3_sdk.apis.email_campaigns_api import EmailCampaignsApi


class TestEmailCampaignsApi(unittest.TestCase):
    """ EmailCampaignsApi unit test stubs """

    def setUp(self):
        self.api = sib_api_v3_sdk.apis.email_campaigns_api.EmailCampaignsApi()

    def tearDown(self):
        pass

    def test_create_email_campaign(self):
        """
        Test case for create_email_campaign

        Create an email campaign
        """
        pass

    def test_delete_email_campaigns(self):
        """
        Test case for delete_email_campaigns

        Delete an email campaign
        """
        pass

    def test_email_export_recipients(self):
        """
        Test case for email_export_recipients

        Export the recipients of a campaign
        """
        pass

    def test_get_email_campaign(self):
        """
        Test case for get_email_campaign

        Get campaign informations
        """
        pass

    def test_get_email_campaigns(self):
        """
        Test case for get_email_campaigns

        Return all your created campaigns
        """
        pass

    def test_send_email_campaign_now(self):
        """
        Test case for send_email_campaign_now

        Send an email campaign id of the campaign immediately
        """
        pass

    def test_send_report(self):
        """
        Test case for send_report

        Send the report of a campaigns
        """
        pass

    def test_send_test_email(self):
        """
        Test case for send_test_email

        Send an email campaign to your test list
        """
        pass

    def test_update_campaign_status(self):
        """
        Test case for update_campaign_status

        Update a campaign status
        """
        pass

    def test_update_email_campaigns(self):
        """
        Test case for update_email_campaigns

        Update a campaign
        """
        pass


if __name__ == '__main__':
    unittest.main()
